## Numpy

Numerical Python

In [2]:
import numpy as np
import pandas as pd

In [3]:
array=np.array(30)
array

array(30)

In [5]:
array=np.array([30,20,45])
array

array([30, 20, 45])

### Access items using indexing and slicing

In [7]:
list1=[4,3,5,6,7,8]
list1[2]

5

In [9]:
list1=[4,3,5,6,7,8]
list1[2:5]

[5, 6, 7]

In [10]:
list1=[4,3,5,6,7,8]
list1[2:-1]

[5, 6, 7]

In [12]:
array1=np.array([4,3,5,6,7,8])
array1

array([4, 3, 5, 6, 7, 8])

In [13]:
array1[2]

5

In [15]:
array1[4]

7

In [18]:
array2=np.array([2,3,4,10,20,30])

In [19]:
array2[1:4]

array([ 3,  4, 10])

In [21]:
array2[3:5]

array([10, 20])

In [22]:
array2[-3:-1]

array([10, 20])

In [23]:
array2[-3:]

array([10, 20, 30])

In [24]:
array3=np.array([2,3,4,10,20,30,40,50])
array3

array([ 2,  3,  4, 10, 20, 30, 40, 50])

In [25]:
array3[1:5:1]

array([ 3,  4, 10, 20])

In [26]:
array3[1:7:2]

array([ 3, 10, 30])

In [28]:
array3[6:1:-1]

array([40, 30, 20, 10,  4])

In [29]:
array3[6:1:-2]

array([40, 20,  4])

In [51]:
array4=np.array([[2,3,4],[10,20,30],[40,50,70]])
array4

array([[ 2,  3,  4],
       [10, 20, 30],
       [40, 50, 70]])

In [49]:
array4[1,2]

30

In [52]:
array4[1][2]

30

In [54]:
array4[2,0]

40

In [55]:
array4=np.array([[2,3,4],[10,20,30],[40,50,70]])
array4

array([[ 2,  3,  4],
       [10, 20, 30],
       [40, 50, 70]])

In [ ]:
import numpy as np

# mine
arr = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])


In [ ]:
element = arr[1, 0, 2]
print(element) 


In [ ]:
slice1 = arr[1:3, :, :]
print(slice1)


In [58]:
array4[0:2,2] #0 and 1 row , 2nd column

array([ 4, 30])

In [59]:
array4[:,2]

array([ 4, 30, 70])

In [60]:
array4[:,1]

array([ 3, 20, 50])

In [62]:
array4[:,:]

array([[ 2,  3,  4],
       [10, 20, 30],
       [40, 50, 70]])

In [64]:
array4[1:]

array([[10, 20, 30],
       [40, 50, 70]])

In [65]:
array4[1:,:2]

array([[10, 20],
       [40, 50]])

### Numpy Functions

## 1. Shape

In [66]:
array3=np.array([2,3,4,10,20,30,40,50])
len(array3)

8

In [67]:
array3.shape

(8,)

In [68]:
array4=np.array([[2,3,4],[10,20,30],[40,50,70]])
array4.shape

(3, 3)

In [71]:
array1=np.array([2,3,4,5,6,7,8,10,20,30,50,60,70])
print('array1',array1)
print('Number of Dimensions :',array1.ndim)

array1 [ 2  3  4  5  6  7  8 10 20 30 50 60 70]
Number of Dimensions : 1


In [72]:
array1=np.array([2,3,4,5,6,7,8,10,20,30,50,60,70],ndmin=2)
print('array1',array1)
print('Number of Dimensions :',array1.ndim)

array1 [[ 2  3  4  5  6  7  8 10 20 30 50 60 70]]
Number of Dimensions : 2


In [73]:
array1=np.array([2,3,4,5,6,7,8,10,20,30,50,60,70],ndmin=3)
print('array1',array1)
print('Number of Dimensions :',array1.ndim)

array1 [[[ 2  3  4  5  6  7  8 10 20 30 50 60 70]]]
Number of Dimensions : 3


## 2. reshape

In [ ]:
used to convert array into n-D array

In [ ]:
There are a lot of functions for changing the shapes of arrays in numpy
flatten, ravel and also for rearranging the elements 
rot90, flip, fliplr, flipud etc.
These fall under Intermediate to Advanced section of numpy.

In [76]:
array1=np.array([2,3,4,5,6,7,8,10,20,30,50,60])
print('array1',array1)
print('Number of Dimensions :',array1.ndim)
print('Shape of Array', array1.shape)

array1 [ 2  3  4  5  6  7  8 10 20 30 50 60]
Number of Dimensions : 1
Shape of Array (12,)


In [ ]:
1*12,2*6,3*4,4*3,6*2,12*1

In [77]:
array1.reshape(2,6)  #2 rows, 6 column

array([[ 2,  3,  4,  5,  6,  7],
       [ 8, 10, 20, 30, 50, 60]])

In [79]:
array1.reshape(12,1) #12 rows, 1 column

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [10],
       [20],
       [30],
       [50],
       [60]])

In [80]:
array1.reshape(3,4) #3 rows, 4 column

array([[ 2,  3,  4,  5],
       [ 6,  7,  8, 10],
       [20, 30, 50, 60]])

In [81]:
array1.reshape(4,3) #4 rows, 3 column

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8, 10, 20],
       [30, 50, 60]])

In [82]:
array1=np.array([2,3,4,5,6,7,8,10,20,30,50,60],ndmin=3)
print('array1',array1)
print('Number of Dimensions :',array1.ndim)
print('Shape of Array', array1.shape)

array1 [[[ 2  3  4  5  6  7  8 10 20 30 50 60]]]
Number of Dimensions : 3
Shape of Array (1, 1, 12)


In [84]:
array1.reshape(2,3,2)

array([[[ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8, 10],
        [20, 30],
        [50, 60]]])

In [85]:
array1.reshape(1,6,2)

array([[[ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8, 10],
        [20, 30],
        [50, 60]]])

### 3. nditer

In [87]:
array1=np.array([2,3,4,5,6,7,8,10,20,30,50,60])
print('array1',array1)
for i in array1:
    print(i)

array1 [ 2  3  4  5  6  7  8 10 20 30 50 60]
2
3
4
5
6
7
8
10
20
30
50
60


In [93]:
array1=np.array([[2,3,4],[5,6,7],[10,20,30]])
print('array1\n',array1)
for i in array1:
    print('row :',i)

array1
 [[ 2  3  4]
 [ 5  6  7]
 [10 20 30]]
row : [2 3 4]
row : [5 6 7]
row : [10 20 30]


In [94]:
array1=np.array([[2,3,4],[5,6,7],[10,20,30]])
print('array1\n',array1)
for i in array1:
    for j in i:
        print(j)

array1
 [[ 2  3  4]
 [ 5  6  7]
 [10 20 30]]
2
3
4
5
6
7
10
20
30


In [98]:
array1=np.array([[2,3,4],[5,6,7],[10,20,30]])
print('array1\n',array1)
for i in np.nditer(array1):
    print(i)

array1
 [[ 2  3  4]
 [ 5  6  7]
 [10 20 30]]
2
3
4
5
6
7
10
20
30


In [12]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:,::-2]):
    print(x)


2
4
6
8


In [100]:
array1=np.array([2,3,4,5,6,7,8,10,20,30,50,60])
for i,val in enumerate(array1):
    print(i,val)

0 2
1 3
2 4
3 5
4 6
5 7
6 8
7 10
8 20
9 30
10 50
11 60


### 4. np.ndenumerate

In [101]:
array1=np.array([[2,3,4],[5,6,7],[10,20,30]])
print('array1\n',array1)
for i in np.nditer(array1):
    print(i)

array1
 [[ 2  3  4]
 [ 5  6  7]
 [10 20 30]]
2
3
4
5
6
7
10
20
30


In [105]:
print('array1\n',array1)
for i, val in np.ndenumerate(array1):
    print(f'{i} >>   {val}')

array1
 [[ 2  3  4]
 [ 5  6  7]
 [10 20 30]]
(0, 0) >>   2
(0, 1) >>   3
(0, 2) >>   4
(1, 0) >>   5
(1, 1) >>   6
(1, 2) >>   7
(2, 0) >>   10
(2, 1) >>   20
(2, 2) >>   30


In [25]:
import numpy as np

arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8],[1, 2, 3, 4], [5, 6, 7, 8]]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
(0, 2, 0) 1
(0, 2, 1) 2
(0, 2, 2) 3
(0, 2, 3) 4
(0, 3, 0) 5
(0, 3, 1) 6
(0, 3, 2) 7
(0, 3, 3) 8


## 5. flatten

In [ ]:
used to convert n-D array into 1-D array

In [107]:
array1=np.array([[2,3,4],[5,6,7],[10,20,30]])
print('array1\n',array1)
array1.shape

array1
 [[ 2  3  4]
 [ 5  6  7]
 [10 20 30]]


(3, 3)

In [108]:
new_array=array1.flatten()
new_array

array([ 2,  3,  4,  5,  6,  7, 10, 20, 30])

### 6. tolist

In [ ]:
used to convert array into list

In [110]:
array1=np.array([2,3,4,5,6,7,8,10,20,30,50,60])
print(type(array1))

x=array1.tolist()
print(type(x))

<class 'numpy.ndarray'>
<class 'list'>


In [111]:
x

[2, 3, 4, 5, 6, 7, 8, 10, 20, 30, 50, 60]

## 7. zeros

In [114]:
array2=np.zeros(10,dtype=int)
array2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [115]:
array2=np.zeros([4,5],dtype=int)
array2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### 8. ones()

In [116]:
array2=np.ones([4,5],dtype=int)
array2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 9. full

In [117]:
array1=np.full(10,2)
array1

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [118]:
array1=np.full(10,5)
array1

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [119]:
array1=np.full(10,0)
array1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [120]:
array1=np.full(10,1)
array1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [121]:
list(range(11,21))

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [122]:
array=np.arange(11,21)
array

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [123]:
array=np.arange(1,21,2)
array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [124]:
array=np.arange(-6,6)
array

array([-6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [127]:
array=np.eye(5,dtype=int)
array

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [128]:
array2=np.identity(7,dtype=int) #identity >> no of rows ==no of columns
array2

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

### 10. random.randint

In [ ]:
used to generate random integers
np.random.randint(start_index,end_index,size=1)

In [138]:
array=np.random.randint(10,15)
array

14

In [142]:
array=np.random.randint(10,100,6)
array

array([89, 90, 95, 29, 14, 29])

In [148]:
array=np.random.randint(10,100,(4,3))
array

array([[86, 82, 95],
       [89, 88, 51],
       [34, 27, 55],
       [45, 82, 43]])